{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPatrSxHjGxbDI3z6EToZta"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "oGOHAnVYAsy1",
        "outputId": "2eeeb917-da34-41d5-8c33-ea482767eeec"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting plaid-python\n",
            "  Downloading plaid_python-34.0.0.tar.gz (1.1 MB)\n",
            "\u001b[?25l     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/1.1 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K     \u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[91m╸\u001b[0m\u001b[90m━━━\u001b[0m \u001b[32m1.0/1.1 MB\u001b[0m \u001b[31m37.5 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.1/1.1 MB\u001b[0m \u001b[31m15.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting streamlit\n",
            "  Downloading streamlit-1.47.0-py3-none-any.whl.metadata (9.0 kB)\n",
            "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)\n",
            "Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (0.13.2)\n",
            "Requirement already satisfied: urllib3>=1.25.3 in /usr/local/lib/python3.11/dist-packages (from plaid-python) (2.4.0)\n",
            "Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from plaid-python) (2.9.0.post0)\n",
            "Collecting nulltype (from plaid-python)\n",
            "  Downloading nulltype-2.3.1-py2.py3-none-any.whl.metadata (10 kB)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.2.1)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (25.0)\n",
            "Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.2.1)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.5.0)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.14.1)\n",
            "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
            "  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.3/44.3 kB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)\n",
            "Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.3)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.1)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.2)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.58.5)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.3)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.24.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.47.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil->plaid-python) (1.17.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.7.14)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2025.4.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.26.0)\n",
            "Downloading streamlit-1.47.0-py3-none-any.whl (9.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.9/9.9 MB\u001b[0m \u001b[31m75.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m81.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m79.1/79.1 kB\u001b[0m \u001b[31m4.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading nulltype-2.3.1-py2.py3-none-any.whl (11 kB)\n",
            "Building wheels for collected packages: plaid-python\n",
            "  Building wheel for plaid-python (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for plaid-python: filename=plaid_python-34.0.0-py3-none-any.whl size=5386359 sha256=a50255ce24d2ec97b6553648003ec7338dc9b5e01b844fa2a9e5b9fdd7bb9865\n",
            "  Stored in directory: /root/.cache/pip/wheels/7c/07/78/259b0a3bfba5a7314c8f50d586c07f7a469c6ac641bf216bda\n",
            "Successfully built plaid-python\n",
            "Installing collected packages: nulltype, watchdog, pydeck, plaid-python, streamlit\n",
            "Successfully installed nulltype-2.3.1 plaid-python-34.0.0 pydeck-0.9.1 streamlit-1.47.0 watchdog-6.0.0\n"
          ]
        }
      ],
      "source": [
        "!pip install plaid-python streamlit scikit-learn pandas matplotlib seaborn"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import requests\n",
        "import time\n",
        "from datetime import datetime"
      ],
      "metadata": {
        "id": "7Q_nS3I8AxrX"
      },
      "execution_count": 13,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "assets_table = pd.DataFrame([\n",
        "    {\"Asset\": \"S&P 500\",         \"AV Symbol\": \"SPY\",      \"AV Type\": \"stock\"},\n",
        "    {\"Asset\": \"Semiconductors\",  \"AV Symbol\": \"SOXX\",     \"AV Type\": \"stock\"},\n",
        "    {\"Asset\": \"Uranium\",         \"AV Symbol\": \"URNM\",     \"AV Type\": \"stock\"},\n",
        "    {\"Asset\": \"Bitcoin\",         \"AV Symbol\": \"BTC\",      \"AV Type\": \"crypto\"},\n",
        "    {\"Asset\": \"Gold\",            \"AV Symbol\": \"GOLD\",     \"AV Type\": \"commodity\"},   # FIXED\n",
        "    {\"Asset\": \"Copper\",          \"AV Symbol\": \"COPPER\",   \"AV Type\": \"commodity\"},  # FIXED\n",
        "    {\"Asset\": \"Oil\",             \"AV Symbol\": \"WTI\",      \"AV Type\": \"commodity\"},\n",
        "])"
      ],
      "metadata": {
        "id": "fcZVWNo_NHH-"
      },
      "execution_count": 23,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def get_av_data(row):\n",
        "    symbol = row['AV Symbol']\n",
        "    asset_type = row['AV Type']\n",
        "    asset = row['Asset']\n",
        "    cache_file = f\"{cache_dir}/{symbol}_{asset_type}.csv\"\n",
        "    if os.path.exists(cache_file):\n",
        "        print(f\"[Cache] {asset}\")\n",
        "        return pd.read_csv(cache_file, parse_dates=['date'], index_col='date')\n",
        "    if not api_key:\n",
        "        raise ValueError(\"No Alpha Vantage API key found in environment variable ALPHAVANTAGE_API_KEY.\")\n",
        "    if asset_type == \"stock\":\n",
        "        params = {\n",
        "            \"function\": \"TIME_SERIES_DAILY\",\n",
        "            \"symbol\": symbol,\n",
        "            \"outputsize\": \"full\",\n",
        "            \"apikey\": api_key,\n",
        "            \"datatype\": \"json\"\n",
        "        }\n",
        "        endpoint = \"https://www.alphavantage.co/query\"\n",
        "    elif asset_type == \"crypto\":\n",
        "        params = {\n",
        "            \"function\": \"DIGITAL_CURRENCY_DAILY\",\n",
        "            \"symbol\": symbol,\n",
        "            \"market\": \"USD\",\n",
        "            \"apikey\": api_key,\n",
        "            \"datatype\": \"json\"\n",
        "        }\n",
        "        endpoint = \"https://www.alphavantage.co/query\"\n",
        "    elif asset_type == \"fx\":\n",
        "        params = {\n",
        "            \"function\": \"FX_DAILY\",\n",
        "            \"from_symbol\": symbol[:3],\n",
        "            \"to_symbol\": symbol[3:],\n",
        "            \"outputsize\": \"full\",\n",
        "            \"apikey\": api_key,\n",
        "            \"datatype\": \"json\"\n",
        "        }\n",
        "        endpoint = \"https://www.alphavantage.co/query\"\n",
        "    elif asset_type == \"commodity\":\n",
        "        params = {\n",
        "            \"function\": symbol,  # 'GOLD', 'COPPER', 'WTI', etc.\n",
        "            \"interval\": \"monthly\",\n",
        "            \"apikey\": api_key,\n",
        "            \"datatype\": \"json\"\n",
        "        }\n",
        "        endpoint = \"https://www.alphavantage.co/query\"\n",
        "    else:\n",
        "        print(f\"Asset type not supported by Alpha Vantage free API: {asset_type}\")\n",
        "        return pd.DataFrame()\n",
        "    print(f\"[API] {asset} ({symbol}, {asset_type})...\")\n",
        "    r = requests.get(endpoint, params=params)\n",
        "    data = r.json()\n",
        "    time.sleep(12.1)\n",
        "    if \"Error Message\" in data or \"Note\" in data or not data:\n",
        "        print(f\"{asset} API error: {data}\")\n",
        "        return pd.DataFrame()\n",
        "    try:\n",
        "        if asset_type == \"stock\":\n",
        "            ts = data.get(\"Time Series (Daily)\", {})\n",
        "            if not ts:\n",
        "                print(f\"No stock/ETF data for {asset}. Response: {data}\")\n",
        "                return pd.DataFrame()\n",
        "            df = pd.DataFrame.from_dict(ts, orient=\"index\")\n",
        "            df.index = pd.to_datetime(df.index)\n",
        "            df = df.rename(columns={\n",
        "                \"1. open\": \"open\",\n",
        "                \"2. high\": \"high\",\n",
        "                \"3. low\": \"low\",\n",
        "                \"4. close\": \"close\",\n",
        "                \"5. volume\": \"volume\"\n",
        "            })\n",
        "            for col in [\"open\", \"high\", \"low\", \"close\", \"volume\"]:\n",
        "                if col not in df.columns: df[col] = np.nan\n",
        "            df = df[[\"open\", \"high\", \"low\", \"close\", \"volume\"]].astype(float)\n",
        "        elif asset_type == \"crypto\":\n",
        "            ts = data.get(\"Time Series (Digital Currency Daily)\", {})\n",
        "            if not ts:\n",
        "                print(f\"No crypto data for {asset}. Response: {data}\")\n",
        "                return pd.DataFrame()\n",
        "            df = pd.DataFrame.from_dict(ts, orient=\"index\")\n",
        "            df.index = pd.to_datetime(df.index)\n",
        "            df = df.rename(columns={\n",
        "                \"1a. open (USD)\": \"open\",\n",
        "                \"2a. high (USD)\": \"high\",\n",
        "                \"3a. low (USD)\": \"low\",\n",
        "                \"4a. close (USD)\": \"close\",\n",
        "                \"5. volume\": \"volume\"\n",
        "            })\n",
        "            for col in [\"open\", \"high\", \"low\", \"close\", \"volume\"]:\n",
        "                if col not in df.columns: df[col] = np.nan\n",
        "            df = df[[\"open\", \"high\", \"low\", \"close\", \"volume\"]].astype(float)\n",
        "        elif asset_type == \"fx\":\n",
        "            ts = data.get(\"Time Series FX (Daily)\", {})\n",
        "            if not ts:\n",
        "                print(f\"No FX data for {asset}. Response: {data}\")\n",
        "                return pd.DataFrame()\n",
        "            df = pd.DataFrame.from_dict(ts, orient=\"index\")\n",
        "            df.index = pd.to_datetime(df.index)\n",
        "            df = df.rename(columns={\n",
        "                \"1. open\": \"open\",\n",
        "                \"2. high\": \"high\",\n",
        "                \"3. low\": \"low\",\n",
        "                \"4. close\": \"close\"\n",
        "            })\n",
        "            for col in [\"open\", \"high\", \"low\", \"close\"]:\n",
        "                if col not in df.columns: df[col] = np.nan\n",
        "            df = df[[\"open\", \"high\", \"low\", \"close\"]].astype(float)\n",
        "        elif asset_type == \"commodity\":\n",
        "            ts = data.get(\"data\", [])\n",
        "            if not ts:\n",
        "                print(f\"No commodity data for {asset}. Response: {data}\")\n",
        "                return pd.DataFrame()\n",
        "            df = pd.DataFrame(ts)\n",
        "            if \"date\" in df.columns:\n",
        "                df['date'] = pd.to_datetime(df['date'])\n",
        "                df = df.set_index('date')\n",
        "            if \"value\" in df.columns:\n",
        "                df = df.rename(columns={\"value\": \"close\"})\n",
        "            if \"close\" in df.columns:\n",
        "                df = df[[\"close\"]].astype(float)\n",
        "        else:\n",
        "            print(f\"Unknown asset type: {asset_type}\")\n",
        "            return pd.DataFrame()\n",
        "        df.index.name = \"date\"\n",
        "        df.to_csv(cache_file)\n",
        "        print(f\"[Saved] {asset} data to cache.\")\n",
        "        return df\n",
        "    except Exception as e:\n",
        "        print(f\"Failed to parse {asset}: {e}\")\n",
        "        return pd.DataFrame()"
      ],
      "metadata": {
        "id": "aWbOlDORNcmN"
      },
      "execution_count": 24,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "for asset, df in asset_data.items():\n",
        "    print(f\"\\n{'='*60}\\n{asset}\")\n",
        "    if df.empty or len(df) < 2:\n",
        "        print(\"No data loaded.\")\n",
        "        continue\n",
        "    print(f\"Shape: {df.shape}\")\n",
        "    print(\"Columns:\", list(df.columns))\n",
        "    print(\"Dtypes:\\n\", df.dtypes)\n",
        "    print(\"\\nHead:\")\n",
        "    print(df.head(2))\n",
        "    print(\"\\nTail:\")\n",
        "    print(df.tail(2))\n",
        "    print(\"\\nDate Range:\")\n",
        "    print(f\"Start: {df.index.min().date()}, End: {df.index.max().date()}\")\n",
        "    print(\"\\nMissing Values Per Column:\")\n",
        "    print(df.isnull().sum())\n",
        "    print(\"\\nDescriptive Stats:\")\n",
        "    print(df.describe().T)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "UlxobebhTVan",
        "outputId": "b611c468-24aa-4f6c-eba8-ff1c6090d8d9"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "============================================================\n",
            "S&P 500\n",
            "Shape: (6466, 5)\n",
            "Columns: ['open', 'high', 'low', 'close', 'volume']\n",
            "Dtypes:\n",
            " open      float64\n",
            "high      float64\n",
            "low       float64\n",
            "close     float64\n",
            "volume    float64\n",
            "dtype: object\n",
            "\n",
            "Head:\n",
            "              open      high     low   close      volume\n",
            "date                                                    \n",
            "2025-07-17  624.40  628.4048  624.18  628.04  68885683.0\n",
            "2025-07-16  623.74  624.7300  618.05  624.22  88987511.0\n",
            "\n",
            "Tail:\n",
            "                open    high       low     close     volume\n",
            "date                                                       \n",
            "1999-11-02  135.9687  137.25  134.5937  134.5937  6516900.0\n",
            "1999-11-01  136.5000  137.00  135.5625  135.5625  4006500.0\n",
            "\n",
            "Date Range:\n",
            "Start: 1999-11-01, End: 2025-07-17\n",
            "\n",
            "Missing Values Per Column:\n",
            "open      0\n",
            "high      0\n",
            "low       0\n",
            "close     0\n",
            "volume    0\n",
            "dtype: int64\n",
            "\n",
            "Descriptive Stats:\n",
            "         count          mean           std        min           25%  \\\n",
            "open    6466.0  2.183280e+02  1.333291e+02      67.95  1.209025e+02   \n",
            "high    6466.0  2.196096e+02  1.339851e+02      70.00  1.215775e+02   \n",
            "low     6466.0  2.169304e+02  1.326167e+02      67.10  1.201300e+02   \n",
            "close   6466.0  2.183498e+02  1.333740e+02      68.11  1.208875e+02   \n",
            "volume  6466.0  1.045717e+08  9.030266e+07  170817.00  4.968140e+07   \n",
            "\n",
            "                 50%           75%           max  \n",
            "open    1.506025e+02  2.809375e+02  6.275200e+02  \n",
            "high    1.514500e+02  2.826400e+02  6.284048e+02  \n",
            "low     1.496281e+02  2.794525e+02  6.241800e+02  \n",
            "close   1.505600e+02  2.811500e+02  6.280400e+02  \n",
            "volume  7.759527e+07  1.325724e+08  8.710263e+08  \n",
            "\n",
            "============================================================\n",
            "Semiconductors\n",
            "Shape: (6038, 5)\n",
            "Columns: ['open', 'high', 'low', 'close', 'volume']\n",
            "Dtypes:\n",
            " open      float64\n",
            "high      float64\n",
            "low       float64\n",
            "close     float64\n",
            "volume    float64\n",
            "dtype: object\n",
            "\n",
            "Head:\n",
            "               open    high      low   close     volume\n",
            "date                                                   \n",
            "2025-07-17  245.535  247.13  243.905  246.53  4801141.0\n",
            "2025-07-16  244.280  245.67  239.215  245.59  8348922.0\n",
            "\n",
            "Tail:\n",
            "             open   high    low  close    volume\n",
            "date                                            \n",
            "2001-07-16  71.35  71.55  68.44  68.44   60000.0\n",
            "2001-07-13  72.30  73.59  70.58  72.65  201100.0\n",
            "\n",
            "Date Range:\n",
            "Start: 2001-07-13, End: 2025-07-17\n",
            "\n",
            "Missing Values Per Column:\n",
            "open      0\n",
            "high      0\n",
            "low       0\n",
            "close     0\n",
            "volume    0\n",
            "dtype: int64\n",
            "\n",
            "Descriptive Stats:\n",
            "         count           mean           std     min          25%          50%  \\\n",
            "open    6038.0     144.768508  1.377527e+02   24.08      53.8500      69.1000   \n",
            "high    6038.0     146.307609  1.393533e+02   24.48      54.3125      69.6900   \n",
            "low     6038.0     143.082216  1.360791e+02   11.26      53.3050      68.4074   \n",
            "close   6038.0     144.768965  1.378370e+02   23.38      53.7600      69.0200   \n",
            "volume  6038.0  646569.740311  1.169264e+06  300.00  119725.0000  302750.0000   \n",
            "\n",
            "                75%          max  \n",
            "open       195.6800       687.38  \n",
            "high       197.8850       696.85  \n",
            "low        193.1600       682.73  \n",
            "close      195.7225       689.60  \n",
            "volume  683345.2500  23539516.00  \n",
            "\n",
            "============================================================\n",
            "Uranium\n",
            "Shape: (1411, 5)\n",
            "Columns: ['open', 'high', 'low', 'close', 'volume']\n",
            "Dtypes:\n",
            " open      float64\n",
            "high      float64\n",
            "low       float64\n",
            "close     float64\n",
            "volume    float64\n",
            "dtype: object\n",
            "\n",
            "Head:\n",
            "             open     high    low  close    volume\n",
            "date                                              \n",
            "2025-07-17  48.56  49.4500  47.92  49.14  534752.0\n",
            "2025-07-16  47.72  48.8193  47.23  48.56  505775.0\n",
            "\n",
            "Tail:\n",
            "             open    high    low   close   volume\n",
            "date                                             \n",
            "2019-12-05  25.21  25.560  25.21  25.478  11449.0\n",
            "2019-12-04  25.14  25.292  25.14  25.226   3975.0\n",
            "\n",
            "Date Range:\n",
            "Start: 2019-12-04, End: 2025-07-17\n",
            "\n",
            "Missing Values Per Column:\n",
            "open      0\n",
            "high      0\n",
            "low       0\n",
            "close     0\n",
            "volume    0\n",
            "dtype: int64\n",
            "\n",
            "Descriptive Stats:\n",
            "         count           mean            std     min          25%        50%  \\\n",
            "open    1411.0      48.534241      18.001644  15.590      33.0850      46.75   \n",
            "high    1411.0      49.279472      18.403635  16.733      33.6452      47.35   \n",
            "low     1411.0      47.548394      17.342036  15.551      32.7500      45.78   \n",
            "close   1411.0      48.411045      17.868530  16.290      33.2100      46.62   \n",
            "volume  1411.0  367037.767541  383377.826972  21.000  105403.5000  270011.00   \n",
            "\n",
            "                 75%           max  \n",
            "open        61.12000  1.036200e+02  \n",
            "high        62.45495  1.040000e+02  \n",
            "low         60.00000  9.884910e+01  \n",
            "close       60.92000  1.022600e+02  \n",
            "volume  506193.50000  3.696337e+06  \n",
            "\n",
            "============================================================\n",
            "Bitcoin\n",
            "Shape: (350, 5)\n",
            "Columns: ['open', 'high', 'low', 'close', 'volume']\n",
            "Dtypes:\n",
            " open      float64\n",
            "high      float64\n",
            "low       float64\n",
            "close     float64\n",
            "volume    float64\n",
            "dtype: object\n",
            "\n",
            "Head:\n",
            "            open  high  low  close       volume\n",
            "date                                           \n",
            "2025-07-18   NaN   NaN  NaN    NaN   153.774827\n",
            "2025-07-17   NaN   NaN  NaN    NaN  8360.351309\n",
            "\n",
            "Tail:\n",
            "            open  high  low  close        volume\n",
            "date                                            \n",
            "2024-08-04   NaN   NaN  NaN    NaN  10319.010917\n",
            "2024-08-03   NaN   NaN  NaN    NaN   8019.394509\n",
            "\n",
            "Date Range:\n",
            "Start: 2024-08-03, End: 2025-07-18\n",
            "\n",
            "Missing Values Per Column:\n",
            "open      350\n",
            "high      350\n",
            "low       350\n",
            "close     350\n",
            "volume      0\n",
            "dtype: int64\n",
            "\n",
            "Descriptive Stats:\n",
            "        count          mean          std         min          25%  \\\n",
            "open      0.0           NaN          NaN         NaN          NaN   \n",
            "high      0.0           NaN          NaN         NaN          NaN   \n",
            "low       0.0           NaN          NaN         NaN          NaN   \n",
            "close     0.0           NaN          NaN         NaN          NaN   \n",
            "volume  350.0  10415.870173  7765.876545  153.774827  4789.905672   \n",
            "\n",
            "                50%           75%           max  \n",
            "open            NaN           NaN           NaN  \n",
            "high            NaN           NaN           NaN  \n",
            "low             NaN           NaN           NaN  \n",
            "close           NaN           NaN           NaN  \n",
            "volume  8977.318069  13324.119917  59125.789267  \n",
            "\n",
            "============================================================\n",
            "Gold\n",
            "No data loaded.\n",
            "\n",
            "============================================================\n",
            "Copper\n",
            "No data loaded.\n",
            "\n",
            "============================================================\n",
            "Oil\n",
            "Shape: (474, 1)\n",
            "Columns: ['close']\n",
            "Dtypes:\n",
            " close    float64\n",
            "dtype: object\n",
            "\n",
            "Head:\n",
            "            close\n",
            "date             \n",
            "2025-06-01  68.17\n",
            "2025-05-01  62.17\n",
            "\n",
            "Tail:\n",
            "            close\n",
            "date             \n",
            "1986-02-01  15.46\n",
            "1986-01-01  22.93\n",
            "\n",
            "Date Range:\n",
            "Start: 1986-01-01, End: 2025-06-01\n",
            "\n",
            "Missing Values Per Column:\n",
            "close    0\n",
            "dtype: int64\n",
            "\n",
            "Descriptive Stats:\n",
            "       count       mean        std    min    25%    50%      75%     max\n",
            "close  474.0  47.907511  29.477915  11.35  20.19  41.03  71.4925  133.88\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import requests\n",
        "import datetime\n",
        "from dateutil.relativedelta import relativedelta\n",
        "\n",
        "# ========== CONFIGURATION ==========\n",
        "ASSETS = {\n",
        "    \"S&P 500\": {\"symbol\": \"SPY\", \"type\": \"stock\"},\n",
        "    \"Semiconductors\": {\"symbol\": \"SOXX\", \"type\": \"stock\"},\n",
        "    \"Uranium\": {\"symbol\": \"URNM\", \"type\": \"stock\"},\n",
        "    \"Oil\": {\"symbol\": \"WTI\", \"type\": \"commodity\"}\n",
        "}\n",
        "MACROS = {\n",
        "    \"CPI\": {\"function\": \"CPI\"},\n",
        "    \"Unemployment\": {\"function\": \"UNEMPLOYMENT\"},\n",
        "    \"10Y Treasury\": {\"function\": \"TREASURY_YIELD\", \"interval\": \"monthly\", \"maturity\": \"10year\"}\n",
        "}\n",
        "AV_API_KEY = os.getenv(\"ALPHAVANTAGE_API_KEY\") or st.text_input(\"Enter your Alpha Vantage API Key:\", type=\"password\")\n",
        "\n",
        "st.set_page_config(page_title=\"Market KPI & Compliance Dashboard\", layout=\"wide\")\n",
        "st.title(\"📊 Automated KPI & Compliance Monitor for Markets\")\n",
        "\n",
        "# ========== DATA LOADING FUNCTIONS ==========\n",
        "@st.cache_data(show_spinner=\"Fetching data...\", ttl=3600)\n",
        "def fetch_stock_daily(symbol):\n",
        "    url = \"https://www.alphavantage.co/query\"\n",
        "    params = dict(function=\"TIME_SERIES_DAILY\", symbol=symbol, outputsize=\"full\", apikey=AV_API_KEY)\n",
        "    r = requests.get(url, params=params)\n",
        "    data = r.json().get(\"Time Series (Daily)\", {})\n",
        "    if not data:\n",
        "        return pd.DataFrame()\n",
        "    df = pd.DataFrame.from_dict(data, orient=\"index\").rename(columns={\n",
        "        \"1. open\": \"open\",\n",
        "        \"2. high\": \"high\",\n",
        "        \"3. low\": \"low\",\n",
        "        \"4. close\": \"close\",\n",
        "        \"5. volume\": \"volume\"\n",
        "    })\n",
        "    df.index = pd.to_datetime(df.index)\n",
        "    for col in [\"open\", \"high\", \"low\", \"close\", \"volume\"]:\n",
        "        if col not in df.columns: df[col] = np.nan\n",
        "    df = df[[\"open\", \"high\", \"low\", \"close\", \"volume\"]].astype(float).sort_index()\n",
        "    return df\n",
        "\n",
        "@st.cache_data(show_spinner=\"Fetching Oil data...\", ttl=3600)\n",
        "def fetch_oil():\n",
        "    url = \"https://www.alphavantage.co/query\"\n",
        "    params = dict(function=\"WTI\", interval=\"monthly\", apikey=AV_API_KEY)\n",
        "    r = requests.get(url, params=params)\n",
        "    data = r.json().get(\"data\", [])\n",
        "    if not data:\n",
        "        return pd.DataFrame()\n",
        "    df = pd.DataFrame(data)\n",
        "    if \"date\" in df.columns:\n",
        "        df[\"date\"] = pd.to_datetime(df[\"date\"])\n",
        "        df = df.set_index(\"date\")\n",
        "    if \"value\" in df.columns:\n",
        "        df = df.rename(columns={\"value\": \"close\"})\n",
        "    df = df[[\"close\"]].astype(float).sort_index()\n",
        "    return df\n",
        "\n",
        "@st.cache_data(show_spinner=\"Fetching macro data...\", ttl=3600)\n",
        "def fetch_macro(function, **kwargs):\n",
        "    url = \"https://www.alphavantage.co/query\"\n",
        "    params = dict(function=function, apikey=AV_API_KEY)\n",
        "    params.update(kwargs)\n",
        "    r = requests.get(url, params=params)\n",
        "    data = r.json().get(\"data\", [])\n",
        "    if not data:\n",
        "        return pd.DataFrame()\n",
        "    df = pd.DataFrame(data)\n",
        "    if \"date\" in df.columns:\n",
        "        df[\"date\"] = pd.to_datetime(df[\"date\"])\n",
        "        df = df.set_index(\"date\")\n",
        "    if \"value\" in df.columns:\n",
        "        df = df.rename(columns={\"value\": function})\n",
        "    df = df[[function]].astype(float).sort_index()\n",
        "    return df\n",
        "\n",
        "# ========== LOAD DATA ==========\n",
        "if not AV_API_KEY:\n",
        "    st.warning(\"Please enter your Alpha Vantage API key above to continue.\")\n",
        "    st.stop()\n",
        "\n",
        "with st.spinner(\"Loading asset data...\"):\n",
        "    data = {}\n",
        "    for asset, meta in ASSETS.items():\n",
        "        if meta[\"type\"] == \"stock\":\n",
        "            df = fetch_stock_daily(meta[\"symbol\"])\n",
        "        elif meta[\"type\"] == \"commodity\":\n",
        "            df = fetch_oil()\n",
        "        else:\n",
        "            df = pd.DataFrame()\n",
        "        data[asset] = df\n",
        "\n",
        "    macros = {}\n",
        "    for mname, mmeta in MACROS.items():\n",
        "        if mname == \"10Y Treasury\":\n",
        "            df = fetch_macro(mmeta[\"function\"], interval=mmeta[\"interval\"], maturity=mmeta[\"maturity\"])\n",
        "        else:\n",
        "            df = fetch_macro(mmeta[\"function\"])\n",
        "        macros[mname] = df\n",
        "\n",
        "# ========== DATA PREP ==========\n",
        "# Resample all assets to monthly close\n",
        "def resample_monthly(df):\n",
        "    if df.empty: return df\n",
        "    if \"close\" in df.columns:\n",
        "        return df[\"close\"].resample(\"M\").last().to_frame(name=\"close\")\n",
        "    return df\n",
        "\n",
        "monthly = {k: resample_monthly(v) for k,v in data.items()}\n",
        "monthly_macros = {}\n",
        "for k,v in macros.items():\n",
        "    if not v.empty:\n",
        "        monthly_macros[k] = v.resample(\"M\").last()\n",
        "\n",
        "# Merge into panel\n",
        "panel = pd.DataFrame(index=monthly[\"S&P 500\"].index)\n",
        "for k, v in monthly.items():\n",
        "    if not v.empty:\n",
        "        panel[f\"{k}_close\"] = v[\"close\"]\n",
        "for k, v in monthly_macros.items():\n",
        "    if not v.empty:\n",
        "        panel[k] = v.iloc[:,0]\n",
        "panel = panel.sort_index().dropna(how=\"all\")\n",
        "\n",
        "# ========== KPI & ALERT LOGIC ==========\n",
        "def rolling_stat(s, window, func):\n",
        "    return s.rolling(window=window, min_periods=window).apply(func)\n",
        "\n",
        "def calc_kpis(df, name):\n",
        "    out = {}\n",
        "    s = df[f\"{name}_close\"].dropna()\n",
        "    if len(s) < 13: return out\n",
        "    out[\"Return_1M\"] = (s.iloc[-1] / s.iloc[-2] - 1) * 100\n",
        "    out[\"Return_3M\"] = (s.iloc[-1] / s.iloc[-4] - 1) * 100\n",
        "    out[\"Return_12M\"] = (s.iloc[-1] / s.iloc[-13] - 1) * 100\n",
        "    out[\"Max_Drawdown\"] = ((s.cummax() - s) / s.cummax()).max() * 100\n",
        "    out[\"Vol_12M\"] = s.pct_change().rolling(12).std().iloc[-1] * np.sqrt(12) * 100\n",
        "    return out\n",
        "\n",
        "kpis = {k: calc_kpis(panel, k) for k in ASSETS.keys()}\n",
        "\n",
        "# ALERT thresholds - user can edit\n",
        "st.sidebar.header(\"Alert Thresholds\")\n",
        "alert_settings = {\n",
        "    \"drawdown\": st.sidebar.slider(\"Max Drawdown Alert (%)\", min_value=5, max_value=50, value=15),\n",
        "    \"volatility\": st.sidebar.slider(\"Volatility Alert (annual %, 12M)\", min_value=10, max_value=60, value=30),\n",
        "    \"cpi\": st.sidebar.slider(\"CPI Alert (%)\", min_value=2, max_value=10, value=4),\n",
        "    \"unemp\": st.sidebar.slider(\"Unemployment Alert (%)\", min_value=3, max_value=15, value=8),\n",
        "    \"treasury\": st.sidebar.slider(\"10Y Treasury Alert (%)\", min_value=1, max_value=10, value=5)\n",
        "}\n",
        "\n",
        "# ========== ALERT ENGINE ==========\n",
        "alerts = []\n",
        "for asset in ASSETS.keys():\n",
        "    if kpis[asset]:\n",
        "        if kpis[asset][\"Max_Drawdown\"] > alert_settings[\"drawdown\"]:\n",
        "            alerts.append({\n",
        "                \"Date\": panel.index[-1].strftime(\"%Y-%m-%d\"),\n",
        "                \"Type\": \"Drawdown\",\n",
        "                \"Asset\": asset,\n",
        "                \"Value\": f\"{kpis[asset]['Max_Drawdown']:.1f}%\",\n",
        "                \"Threshold\": f\"{alert_settings['drawdown']}%\",\n",
        "                \"Action\": \"Review portfolio/risk allocation\"\n",
        "            })\n",
        "        if kpis[asset][\"Vol_12M\"] > alert_settings[\"volatility\"]:\n",
        "            alerts.append({\n",
        "                \"Date\": panel.index[-1].strftime(\"%Y-%m-%d\"),\n",
        "                \"Type\": \"Volatility\",\n",
        "                \"Asset\": asset,\n",
        "                \"Value\": f\"{kpis[asset]['Vol_12M']:.1f}%\",\n",
        "                \"Threshold\": f\"{alert_settings['volatility']}%\",\n",
        "                \"Action\": \"Increase monitoring/review hedges\"\n",
        "            })\n",
        "\n",
        "# Macro alerts\n",
        "if not panel.empty:\n",
        "    last = panel.iloc[-1]\n",
        "    if \"CPI\" in last and last[\"CPI\"] > alert_settings[\"cpi\"]:\n",
        "        alerts.append({\n",
        "            \"Date\": panel.index[-1].strftime(\"%Y-%m-%d\"),\n",
        "            \"Type\": \"Macro\",\n",
        "            \"Asset\": \"CPI\",\n",
        "            \"Value\": f\"{last['CPI']:.2f}%\",\n",
        "            \"Threshold\": f\"{alert_settings['cpi']}%\",\n",
        "            \"Action\": \"Review inflation hedges/operations\"\n",
        "        })\n",
        "    if \"Unemployment\" in last and last[\"Unemployment\"] > alert_settings[\"unemp\"]:\n",
        "        alerts.append({\n",
        "            \"Date\": panel.index[-1].strftime(\"%Y-%m-%d\"),\n",
        "            \"Type\": \"Macro\",\n",
        "            \"Asset\": \"Unemployment\",\n",
        "            \"Value\": f\"{last['Unemployment']:.2f}%\",\n",
        "            \"Threshold\": f\"{alert_settings['unemp']}%\",\n",
        "            \"Action\": \"Review labor strategy\"\n",
        "        })\n",
        "    if \"10Y Treasury\" in last and last[\"10Y Treasury\"] > alert_settings[\"treasury\"]:\n",
        "        alerts.append({\n",
        "            \"Date\": panel.index[-1].strftime(\"%Y-%m-%d\"),\n",
        "            \"Type\": \"Macro\",\n",
        "            \"Asset\": \"10Y Treasury\",\n",
        "            \"Value\": f\"{last['10Y Treasury']:.2f}%\",\n",
        "            \"Threshold\": f\"{alert_settings['treasury']}%\",\n",
        "            \"Action\": \"Review financing/borrowing plans\"\n",
        "        })\n",
        "\n",
        "# ========== DASHBOARD PANELS ==========\n",
        "\n",
        "# KPIs\n",
        "st.header(\"Key Performance Indicators (KPIs)\")\n",
        "kpi_cols = st.columns(len(ASSETS))\n",
        "for idx, (asset, vals) in enumerate(kpis.items()):\n",
        "    with kpi_cols[idx]:\n",
        "        st.subheader(asset)\n",
        "        for name, val in vals.items():\n",
        "            st.metric(name.replace(\"_\", \" \"), f\"{val:.2f}\")\n",
        "\n",
        "# Macro KPIs\n",
        "st.header(\"Macro Indicators\")\n",
        "macro_cols = st.columns(len(monthly_macros))\n",
        "for idx, (macro, df) in enumerate(monthly_macros.items()):\n",
        "    latest = df.iloc[-1,0] if not df.empty else np.nan\n",
        "    with macro_cols[idx]:\n",
        "        st.subheader(macro)\n",
        "        st.metric(\"Latest\", f\"{latest:.2f}\")\n",
        "\n",
        "# Alerts\n",
        "st.header(\"🔔 Compliance & Anomaly Alerts\")\n",
        "if alerts:\n",
        "    st.dataframe(pd.DataFrame(alerts))\n",
        "else:\n",
        "    st.success(\"No alerts triggered for current period.\")\n",
        "\n",
        "# Executive Summary\n",
        "st.header(\"Executive Summary\")\n",
        "summary = []\n",
        "if alerts:\n",
        "    summary.append(f\"ALERTS ({len(alerts)}):\")\n",
        "    for a in alerts:\n",
        "        summary.append(f\"- {a['Date']} | {a['Asset']} | {a['Type']} at {a['Value']} (Threshold: {a['Threshold']}): {a['Action']}\")\n",
        "else:\n",
        "    summary.append(\"✅ All KPIs and macro indicators within compliance thresholds. No action needed.\")\n",
        "\n",
        "st.write(\"\\n\".join(summary))\n",
        "\n",
        "# Audit log (last 12 months of drawdown/vol)\n",
        "st.header(\"Audit Log (Recent KPI Trends)\")\n",
        "for asset in ASSETS.keys():\n",
        "    s = panel[f\"{asset}_close\"].dropna()\n",
        "    if len(s) >= 13:\n",
        "        drawdown = ((s.cummax() - s) / s.cummax()) * 100\n",
        "        vol = s.pct_change().rolling(12).std() * np.sqrt(12) * 100\n",
        "        st.subheader(f\"{asset} Drawdown & Volatility\")\n",
        "        st.line_chart(pd.DataFrame({\"Drawdown (%)\": drawdown, \"Volatility (Ann. %)\": vol}))\n",
        "\n",
        "# ========== END DASHBOARD ==========\n",
        "st.caption(\"Built by Michael E Williams | Automated KPI & Compliance Monitor | Powered by Alpha Vantage Free API\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "F1m_5vdIUt0B",
        "outputId": "47d727cd-94d1-453d-a302-ce87cd368f4d"
      },
      "execution_count": 28,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-07-18 17:12:56.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.683 No runtime found, using MemoryCacheStorageManager\n",
            "2025-07-18 17:12:56.686 No runtime found, using MemoryCacheStorageManager\n",
            "2025-07-18 17:12:56.689 No runtime found, using MemoryCacheStorageManager\n",
            "2025-07-18 17:12:56.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "/tmp/ipython-input-28-1248686030.py:112: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.\n",
            "  return df[\"close\"].resample(\"M\").last().to_frame(name=\"close\")\n",
            "/tmp/ipython-input-28-1248686030.py:119: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.\n",
            "  monthly_macros[k] = v.resample(\"M\").last()\n",
            "2025-07-18 17:12:56.774 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.796 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.800 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.808 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.809 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.819 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.820 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.827 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.828 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.844 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.844 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.845 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.846 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.847 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.847 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.854 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.854 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.855 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.857 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.859 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.864 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.866 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.871 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.872 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.874 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.874 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.879 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.891 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.905 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.916 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:56.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.165 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.166 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.169 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.342 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-18 17:12:57.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "DeltaGenerator()"
            ]
          },
          "metadata": {},
          "execution_count": 28
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "c2gYDcEbXac8"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}